services:
    asquel.aspect.cacheable:
        class: AsQuel\AopCacheBundle\Service\CachingAspect
        calls:
            - [ setContainer, [ '@service_container' ]]
        arguments:
            - %asquel.cacheable.default_cache_service_adapter%
            - %asquel.cacheable.disabled_methods%
            - %asquel.cacheable.default_ttl%
        tags:
            - { name: goaop.aspect }
